### PR TITLE
Support GIF generation in the PoseVisualizer

### PR DESCRIPTION
**Pull request by AmitMY**
It's more complicated to show videos in Google Colab than GIFs, so I added support

```python
from IPython.display import Image
display(Image(open('test.gif','rb').read()))
```

test_256

### CODE REVIEW

**Review by bricksdont — APPROVED** [review]
I tested this and it works fine,

however I think from a user perspective we badly need more documentation e.g. regarding visualization, including gifs in Colab. This could go in the README or elsewhere

**Comment by bricksdont** [comment]
Possible section to add to README:

## Visualization

Visualize an existing pose file:

```python
from pose_format import Pose
from pose_format.pose_visualizer import PoseVisualizer

p = Pose.read(open("example.pose", "rb").read())

v = PoseVisualizer(p)

v.save_video("example.mp4", v.draw())
```

Draw pose on top of video:

```python
v.save_video("example.mp4", v.draw_on_video())
```

Convert pose to gif to easily inspect the result in Colab:

```python
# in a Colab notebook

from IPython.display import Image

v.save_gif("test.gif", v.draw())

display(Image(open('test.gif','rb').read()))
```

**Comment by bricksdont** [comment]
you could either add this in this PR, or I could add it later

**Comment by AmitMY** [comment]
Added! Thanks

**Comment by bricksdont** [comment]
now looks good to me and a very useful feature, ship it 👍

**Pull request merged**
